/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/patient/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign up as a patient */
        post: operations["patient_signup_api_auth_patient_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/doctor/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign up as a doctor (dummy license verify) */
        post: operations["doctor_signup_api_auth_doctor_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Africa's Talking inbound-call callback
         * @description Accepts `application/x-www-form-urlencoded` (callerNumber, sessionId, isActive) and returns TwiML XML (`<Say>`, `<GetDigits>`, `<Record>`, `<Dial>`).
         */
        post: operations["voice_webhook_api_voice_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recording-consent IVR callback
         * @description Accepts form-data (`conversation_id`, `dtmfDigits`) and returns TwiML XML. Digit 1 starts recorded triage turns; anything else escalates without recording.
         */
        post: operations["voice_consent_api_voice_consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One recorded triage turn
         * @description Accepts form-data (`conversation_id`, `recordingUrl`, `recording_consent`), runs STT → safety/triage → auto-routing, and returns the next TwiML XML prompt including the appointment time once triage is reached.
         */
        post: operations["voice_recording_api_voice_recording_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my appointments
         * @description Patient-facing: their own appointment dates, most recent first.
         */
        get: operations["list_my_appointments_api_appointments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto-book earliest free doctor slot
         * @description Book the earliest free doctor slot for a triaged conversation.
         *
         *     Called by the web-voice client after TRIAGE_UPDATE; the phone channel
         *     calls the same function internally in voice_webhook.py.
         */
        post: operations["route_my_appointment_api_appointments_route_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My conversation history with triage outcomes
         * @description Patient-facing: past triage conversations with the agent, each with
         *     its triage outcome (if one was reached).
         */
        get: operations["list_my_conversation_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prescriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My prescription inbox
         * @description Patient-facing prescription inbox.
         */
        get: operations["list_my_prescriptions_api_prescriptions_get"];
        put?: never;
        /**
         * Send a prescription to a patient
         * @description Clinician-facing: send a prescription to a patient.
         */
        post: operations["create_prescription_api_prescriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinician/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my weekly availability
         * @description Doctor's own weekly windows (UTC, HH:MM).
         */
        get: operations["get_my_availability_api_clinician_availability_get"];
        /**
         * Replace my weekly availability
         * @description Replace all weekly windows. A weekday with no window means unavailable.
         */
        put: operations["set_my_availability_api_clinician_availability_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinician/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My appointment queue with triage reports
         * @description Clinician-facing: pending/upcoming appointments, most urgent first
         *     (RED > AMBER > GREEN, matching the pipeline's urgency_tier), each with
         *     the patient details and the voice-agent triage report embedded.
         */
        get: operations["get_appointment_queue_api_clinician_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinician/patients/{patient_id}/triage-form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Triage report for one assigned patient
         * @description Clinician-facing: the structured fields, danger signs, and summary
         *     captured for one patient's triage conversation. Access is scoped to
         *     patients this clinician has an appointment with — matching the RLS
         *     policy shape exactly, not just the active queue.
         */
        get: operations["get_patient_triage_form_api_clinician_patients__patient_id__triage_form_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calls/click-to-call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Doctor bridges a call for an appointment
         * @description Clinician-facing call button: bridges the clinic's calling number
         *     and the patient's number for a specific appointment.
         *
         *     Recording only starts if consent_confirmed is explicitly true — per
         *     RULES.md rule 4, never record silently.
         */
        post: operations["click_to_call_api_calls_click_to_call_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calls/patient-join/{appointment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Patient joins their appointment call
         * @description Patient-facing call button: dials the patient's own on-file number
         *     to connect them into their appointment call.
         */
        post: operations["patient_join_call_api_calls_patient_join__appointment_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calls/{call_recording_id}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize a call transcript for the record
         * @description Stores an LLM-extracted key-points summary of a call transcript for
         *     the doctor's record.
         *
         *     NOTE: this takes the transcript as input rather than transcribing a
         *     recording itself. Sahara's file-upload STT endpoint (needed to
         *     transcribe a completed call recording after the fact) is still
         *     unconfirmed against real docs — wire that in ahead of this once
         *     confirmed, rather than assuming a schema for it here.
         */
        post: operations["summarize_call_api_calls__call_recording_id__summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppointmentListResponse */
        AppointmentListResponse: {
            /** Appointments */
            appointments: components["schemas"]["AppointmentOut"][];
        };
        /** AppointmentOut */
        AppointmentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Tier
             * @example AMBER
             */
            tier: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Doctor Id */
            doctor_id?: string | null;
            /**
             * Status
             * @example scheduled
             */
            status: string;
            /** Notified Via */
            notified_via?: string | null;
        };
        /** AvailabilityResponse */
        AvailabilityResponse: {
            /** Windows */
            windows: components["schemas"]["AvailabilityWindowOut"][];
        };
        /** AvailabilityUpdate */
        AvailabilityUpdate: {
            /** Windows */
            windows: components["schemas"]["AvailabilityWindow"][];
        };
        /** AvailabilityWindow */
        AvailabilityWindow: {
            /** Weekday */
            weekday: number;
            /** Start */
            start: string;
            /** End */
            end: string;
        };
        /** AvailabilityWindowOut */
        AvailabilityWindowOut: {
            /** Id */
            id?: string | null;
            /** Doctor Id */
            doctor_id?: string | null;
            /**
             * Weekday
             * @description 0=Monday..6=Sunday (UTC)
             * @example 1
             */
            weekday: number;
            /**
             * Start Time
             * @example 09:00:00
             */
            start_time: string;
            /**
             * End Time
             * @example 12:00:00
             */
            end_time: string;
        };
        /** CallSummaryResponse */
        CallSummaryResponse: {
            /** Key Points Summary */
            key_points_summary: string;
        };
        /** ClickToCallRequest */
        ClickToCallRequest: {
            /**
             * Appointment Id
             * Format: uuid
             */
            appointment_id: string;
            /** Patient Phone Number */
            patient_phone_number: string;
            /** Consent Confirmed */
            consent_confirmed: boolean;
        };
        /** ClickToCallResponse */
        ClickToCallResponse: {
            /** Session Id */
            session_id: string;
            /** Call Recording */
            call_recording?: {
                [key: string]: unknown;
            } | null;
        };
        /** ConversationHistoryItem */
        ConversationHistoryItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Channel */
            channel?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Status */
            status?: string | null;
            /** Triage Result */
            triage_result?: {
                [key: string]: unknown;
            } | null;
        };
        /** DoctorSignup */
        DoctorSignup: {
            /** Name */
            name: string;
            /** Phone Number */
            phone_number: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** License Number */
            license_number: string;
            /** Specialty */
            specialty: string;
            /** Confirm License */
            confirm_license: boolean;
        };
        /** DoctorSignupResponse */
        DoctorSignupResponse: {
            /**
             * Doctor Id
             * Format: uuid
             */
            doctor_id: string;
            /**
             * Access Token
             * @description Supabase session JWT. Null until email confirmed.
             */
            access_token?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Detail
             * @example Not a recognized patient session
             */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Conversations */
            conversations: components["schemas"]["ConversationHistoryItem"][];
        };
        /** PatientJoinResponse */
        PatientJoinResponse: {
            /** Session Id */
            session_id: string;
        };
        /** PatientSignup */
        PatientSignup: {
            /** Name */
            name: string;
            /** Phone Number */
            phone_number: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** PatientSignupResponse */
        PatientSignupResponse: {
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /**
             * Access Token
             * @description Supabase session JWT. Null when 'Confirm email' is enabled until the user confirms.
             */
            access_token?: string | null;
        };
        /** Prescription */
        Prescription: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /**
             * Doctor Id
             * Format: uuid
             */
            doctor_id: string;
            /** Medication */
            medication: string;
            /** Dosage */
            dosage: string;
            /** Instructions */
            instructions: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Status */
            status: string;
        };
        /** PrescriptionCreateRequest */
        PrescriptionCreateRequest: {
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /** Medication */
            medication: string;
            /** Dosage */
            dosage: string;
            /** Instructions */
            instructions: string;
        };
        /** PrescriptionCreateResponse */
        PrescriptionCreateResponse: {
            prescription: components["schemas"]["Prescription"];
        };
        /** PrescriptionListResponse */
        PrescriptionListResponse: {
            /** Prescriptions */
            prescriptions: components["schemas"]["Prescription"][];
        };
        /** QueueItemOut */
        QueueItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Tier
             * @example AMBER
             */
            tier: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Doctor Id */
            doctor_id?: string | null;
            /**
             * Status
             * @example scheduled
             */
            status: string;
            /** Notified Via */
            notified_via?: string | null;
            patient?: components["schemas"]["QueuePatient"] | null;
            /**
             * Triage Report
             * @description Voice-agent triage report: conversation_id, fields, and triage_result.
             */
            triage_report?: {
                [key: string]: unknown;
            } | null;
        };
        /** QueuePatient */
        QueuePatient: {
            /** Name */
            name?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /** Email */
            email?: string | null;
        };
        /** QueueResponse */
        QueueResponse: {
            /** Appointments */
            appointments: components["schemas"]["QueueItemOut"][];
        };
        /** RouteAppointmentRequest */
        RouteAppointmentRequest: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
        };
        /** RouteAppointmentResponse */
        RouteAppointmentResponse: {
            appointment: components["schemas"]["AppointmentOut"];
        };
        /** SummarizeCallRequest */
        SummarizeCallRequest: {
            /** Transcript */
            transcript: string;
        };
        /** TriageFormResponse */
        TriageFormResponse: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Conversation Started At */
            conversation_started_at?: string | null;
            /**
             * Fields
             * @example {
             *       "chief_complaint": "fever",
             *       "symptom_onset": "today"
             *     }
             */
            fields: {
                [key: string]: unknown;
            };
            /** Triage Result */
            triage_result?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    patient_signup_api_auth_patient_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientSignup"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientSignupResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    doctor_signup_api_auth_doctor_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorSignup"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorSignupResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    voice_webhook_api_voice_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Invalid webhook secret */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    voice_consent_api_voice_consent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Invalid webhook secret */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    voice_recording_api_voice_recording_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Invalid webhook secret */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_my_appointments_api_appointments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    route_my_appointment_api_appointments_route_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteAppointmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteAppointmentResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_my_conversation_history_api_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_my_prescriptions_api_prescriptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrescriptionListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_prescription_api_prescriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrescriptionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrescriptionCreateResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_availability_api_clinician_availability_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    set_my_availability_api_clinician_availability_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_appointment_queue_api_clinician_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_patient_triage_form_api_clinician_patients__patient_id__triage_form_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageFormResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    click_to_call_api_calls_click_to_call_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClickToCallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClickToCallResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patient_join_call_api_calls_patient_join__appointment_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientJoinResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    summarize_call_api_calls__call_recording_id__summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_recording_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummarizeCallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallSummaryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
